# Generated by Django 2.0 on 2018-08-30 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlsapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='code',
        ),
        migrations.RemoveField(
            model_name='url',
            name='id',
        ),
        migrations.RemoveField(
            model_name='url',
            name='url',
        ),
        migrations.AddField(
            model_name='url',
            name='url_long',
            field=models.CharField(default=None, max_length=250, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='url',
            name='url_short',
            field=models.CharField(default='pbsdhf', max_length=10, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
